#spring.jpa.properties.hibernate.jdbc.batch_size=20
server.port: 9090

spring:
 jpa:
   properties:
     hibernate:
       jdbc:
         batch_size: 20
 profiles.active: dev
 cloud:
   gcp:
     project-id: sab-ors-poc-sbx-01-9096
     credentials:
       location: classpath:cred.json
     spanner:
       instance-id: instance-1
       database: database-1

## logging
logging:
  pattern.console: '%d{yyyy-MM-dd HH:mm:ss} [%X{source}] [%X{correlation-id}] [%-5level] [%C:%L] - %m%n'
  file: logs/outbox-poller/poller.log
  level.org.springframework: info

# actuator properties
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always
  info.git.mode: full

info:
  app:
    name: pnr-order-poc
    description: Google cloud spanner poller  
    version: 1.0.0
    java-vendor: ${java.specification.vendor}


---
spring.profiles: dev

---
spring.profiles: test

---
spring.profiles: prod

---
spring.profiles: emulator

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20
  cloud:
    gcp:
      project-id: sab-ors-poc-sbx-01-9096
      spanner:
        emulator:
          enabled: false
        emulator-host: localhost:9010
        instance-id: instance-1
        database: database-1